import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Navbar />
      <div className="p-10">
        <Head>
          <title>Web dev practice</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <ul>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/cors">
                CORS
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/http">
                HTTP Protocols
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/http">
                HTTP methods
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/headers">
                Headers and Cookies
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/jwt">
                JWT
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/auth">
                Authorization
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/authentication">
                Authentication
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/csrf">
                CSRF Tokens
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/ws">
                Websockets
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/rate">
                Rate limiting
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/aggregate">
                Aggregations
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/sql">
                SQL Injection
              </a>
            </li>
            <li>
              <a target="_blank" className=" hover:text-red-500" href="/xss">
                XSS Attacks
              </a>
            </li>
          </ul>
        </div>
      </div>
    </>
  );
}
