import Head from "next/head";
import Navbar from "../components/Navbar";
import Typewriter from "typewriter-effect";
import { useEffect, useContext } from "react";

import AuthContext from "../Providers/AuthContext";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  const { state, setState } = useContext(AuthContext);
  useEffect(() => {
    if (state) {
      router.push("/home");
    }
  }, [state]);
  
  return (
    <>
      <Navbar />
      <div className="p-10">
        <Head>
          <title>Web dev practice</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <p className="font-mono text-xl">
          <Typewriter
            onInit={(typewriter) => {
              typewriter
                .typeString("Welcome")
                .pauseFor(1000)
                .deleteAll()
                .typeString("This site tests out your WebD knowledge")
                .start()
                .pauseFor(1000)
                .deleteAll()
                .typeString("Please Enjoy!")
                .start();
            }}
          />
        </p>
      </div>
    </>
  );
}
